version: "3.8"

services:
  discord-sil-bot:
    image: node:22

    container_name: discord-sil-bot

    working_dir: /app

    volumes:
      - ./:/app

    init: true
    shm_size: "1gb"

    env_file:
      - .env

    command: >
      sh -c "
      apt-get update &&
      apt-get install -y chromium &&
      npm install &&
      node src/index.js
      "

    restart: unless-stopped
