version: '3.8'

services:
  discord-sil-bot-prod:
    image: discord-sil-bot:1.0
    container_name: discord-sil-bot-prod

    working_dir: /app

    volumes:
      - /data/local/docker/discord-sil-bot:/app

    init: true
    shm_size: "1gb"

    command: >
      sh -c "
      chown -R node:node /app &&
      su node -s /bin/sh -c 'npm install && node src/index.js'
      "

    restart: unless-stopped